name: kittygram

volumes:
  static:
  media:
  pg_data:

services:
  postgres:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: websevee/kittygram_backend:latest
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - postgres

  frontend:
    image: websevee/kittygram_frontend:latest
    volumes:
      - static:/app/build

  gateway:
    image: websevee/kittygram_gateway:latest
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/media

