name: kittygram

volumes:
  static:
  media:
  pg_data:

services:
  postgres:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    command: >
      sh -c "python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - postgres

  frontend:
    build: ./frontend/
    volumes:
      - static:/app/build

  gateway:
    build: ./nginx/
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/media

