#cloud-config
ssh_pwauth: no
users:
  - name: user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - "${SSH_KEY}"
write_files:
  - content: |
      #!/bin/bash

      # Опишите установку Docker
      sudo apt-get update
      sudo apt-get install -y docker.io
      sudo apt-get install -y docker-compose-plugin
      sudo usermod -aG docker $USER

    path: "/root/vm_prep.sh"
    permissions: "0740"

runcmd:
  - sleep 120
  - sudo -i
  - /root/vm_prep.sh
